### ISSUE TITLE
Dødt link

### ISSUE THREAD

**Issue by fuglede** [christianpanton/visitationszone#17]
Linket http://www.dr.dk/DR2/D/Der_er_noget_galt_i_Danmark/De_6_film/smith.htm, til "Der var engang en retsstat", er dødt.

**Comment by Casper-O** [comment]
Jeg ved ikke med @christianpanton, men ser ud til der ligger et 6 min klip på Youtube med samme titel, ved dog ikke om det samme og om man bør linke til den istedet eller helt fjerne linket?
