### ISSUE TITLE
Politi indfører visitationszone i Aarhus Vest

### ISSUE THREAD

**Issue by kokke** [christianpanton/visitationszone#24]
http://www.dr.dk/nyheder/indland/efter-eskalering-af-bandekonflikt-politi-indfoerer-visitationszone-i-aarhus-vest

> 26. jun. 2017 kl. 09.26
> Politi indfører visitationszone i Aarhus Vest
> 
> Søndag klokken 19:00 indførte politiet visitationszone i Aarhus Vest. Det sker på grund af de seneste ugers konflikt mellem bander. 
> 
> Visitationszone gælder til 24. juli
> 
> Visitationszonen gælder til den 24. juli og strækker sig over et stort område, der dækker byerne Brabrand, Grimhøj og Skjoldhøj.
> 
> Visitationszonen strækker sig helt ind til bydelen Åbyhøj og omfatter området, der er afgrænset af:
> 
> Viborgvej mod nord, Ørvadsvej/Brabrandstien mod syd, Anelystvej mod vest, Haslevej/Tingvej/Viby Ringvej mod øst.

**Comment by Casper-O** [comment]
Hej det ville være en stor hjælp hvis du kunne oprette en optegnelse på følgende link:

https://visitationszone.dk/draw.html

**Comment by christianpanton** [comment]
Done.
